version: '3.4'
services:
  mysql:
    container_name: MySQL
    restart: always
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'root'
      MYSQL_PASS: '123456'
    volumes:
      - ./mysql-5.6.1:/var/lib/mysql
    ports:
      - 3306:3306